/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms. */

let fibonacci1 = 0;
let fibonacci2 = 1;
let newFibonacci = fibonacci1 + fibonacci2;
let summation = 0;

while (newFibonacci <= 4000000) {
  fibonacci1 = fibonacci2;
  fibonacci2 = newFibonacci;
  newFibonacci = fibonacci1 + fibonacci2;

  if (fibonacci2 % 2 == 0) {
    summation += fibonacci2;
  }

  // console.log(fibonacci2);
}

console.log(summation);
